### PR TITLE
GDPR-compliance / GeoIP - Auto Opt-In for non-EEA visitors. #72

### PR DESCRIPTION
**Pull request by claudio-vellage**
I added the feature I requested in #72 earlier this day. I've also switched the GeoIP api to api.ipdata.co #66 because I noticed a deprecation warning in the JSON output of freegeoip.net. After switching to api.ipdata.co, #65 has also been resolved.

### CODE REVIEW

**Comment by ToX82** [comment]
Thanks a lot for your PR!
I love the auto opt-in feature, though I'm asking myself if that should be the default behavior... it's probably wrong that the CookieAccepted cookie can never be set for a user outside of the EU, what do you think? Also the refresh option could be the default behavior.

So the question is: should we have it as an option or we sould make it the default behavior? What do you think?

Finally, after a quick chat with the ipdata.co support, they have kindly agreed to allow the cookiebar to switch to their systems so... we have a new geoip provider :)

**Comment by claudio-vellage** [comment]
I added a check for the refresh option as well after the cookie has been set because otherwise the ads still wouldn't load after the cookie has been set. I don't think this should be the default behavior, because people might want to use the cookie bar for other purposes, also changing the API now (e.g. refresh=1 to noRefresh=1, then inverting all if clauses), might break existing websites. If you want, I can create an updated PR with the refresh after the cookie has been set.

Edit: I also think it's wrong that the cookie is not set, but then again there might be use cases, where people only check for CookiesDisallowed, so not setting the cookie simply means they haven't opted out yet. I'm already using the updated version from my fork in production (via rawgit CDN) and I'm satisfied with the results.

**Comment by ToX82** [comment]
Those are good points indeed. What I'd like to obtain is to have as less configurable options as possible, to make it easier for the users that need to install cookiebar into their websites.

I think that for the users outside of EU we should just set the `CookieAllowed` cookie to true, and decide wether to do the refresh according to the "Refresh page on CookieAllowed" configuration option.

What do you think?

P.S. Sorry for the delay, I'm pretty busy these days...

**Comment by claudio-vellage** [comment]
I agree. One could just remove the autoOptIn parameter and set the cookie by default. I doubt this would actually break someone’s code.

In case someone wants to give non-EU visitors the option to opt out, one could just use the noGeoIp parameter to always show the cookiebar.

**Comment by ToX82** [comment]
I've already made the switch to api.ipdata.co since it was non deferrable anymore :)

Would you like to create a new pull request for the other modifications for the non-EU users?

**Comment by ToX82** [comment]
Auto opt-in for non EEA users has been solved in the latest release, 1.6.2. I'm closing this

**Pull request closed without merging**
